name: 'Terraform Apply'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup_backend:
    name: 'Setup Backend'
    uses: ./.github/workflows/terraform-backend-setup.yml
    secrets: inherit

  terraform:
    name: 'Terraform Apply'
    needs: setup_backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      env:
        TF_VAR_auth0_domain: ${{ secrets.AUTH0_DOMAIN }}
        TF_VAR_auth0_audience: ${{ secrets.AUTH0_AUDIENCE }}
        TF_VAR_auth0_client_secret: ${{ secrets.AUTH0_CLIENT_SECRET }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_auth0_domain: ${{ secrets.AUTH0_DOMAIN }}
        TF_VAR_auth0_audience: ${{ secrets.AUTH0_AUDIENCE }}
        TF_VAR_auth0_client_secret: ${{ secrets.AUTH0_CLIENT_SECRET }} 